v2connectionURL=wss://api.gemini.com/v2/marketdata/l2
v1connectionURL=wss://api.gemini.com/v1/marketdata/BTCUSD
spring.main.web-environment=false
spring.main.lazy-initialization=true
management.endpoints.web.exposure.include=startup
v1.enabled=true
v2.enabled=false
